### ISSUE TITLE
Step 8: ⚙️ Set Up a Team Workflow

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/voyage-template#10]
**__Task Description__**
- [ ] Decide on the coding standards the team must follow.
- [ ] Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- [ ] Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- [ ] Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- [ ] Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to [Reaching your MVP](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#sprint-3-5---reaching-your-mvp) to learn more about the types of meetings you’ll need.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Setup Your Team Workflow (Chingu Handbook)](https://www.notion.so/chingucohorts/Voyages-1e528dcbf1d241c9a93b4627f6f1c809#04c66351937d48b589d835164a4ca0d5](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#7-setup-your-team-workflow))
[Javascript Style Guides](https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa)
[Defining a Git Workflow (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/resources/techresources/gitgithub.md#the-workflow)
[Git Branches (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/resources/techresources/gitgithub.md#git-branches)
[Git Pull Requests (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/resources/techresources/gitgithub.md#git-pull-requests)

**Member of Epic:** #16
