### ISSUE TITLE
Getting Started: 🤔 Start thinking about project ideas & the technical stack

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/voyage-template#3]
**__Task Description__**
- [ ] Check out apps that Voyage teams have created in prior Voyage by reviewing the [Project Showcase](https://medium.com/chingu/chingu-fall-project-showcase-c6bf0f8210ab)
- [ ] Come up with 1 to 3 ideas for projects you'd like to build so you can discuss them with the rest of the team when the Voyage starts.
- [ ] Think about what technical stack you'd like to use to build that app. Similarly, you'll discuss this as a team at the start of the Voyage.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a

**__Resources__**
[Choose a project & create a Vision Statement (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#3-choose-a-project--create-a-vision-statement)

**Member of Epic:** #15
