### ISSUE TITLE
Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/voyage-template#6]
**__Task Description__**
- [ ] Using everyone's availability posted to [When2Meet](https://www.when2meet.com/) schedule a Kickoff meeting
- [ ] Use the Kickoff meeting template in the `docs` directory of your team repo. We've provided this as a tool you can use to help you guide the discussion, record notes, decisions, and assignments.
- [ ] Set a time for your next meeting for later in the week

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a

**__Resources__**
[Conduct Kickoff Meeting (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#2-conduct-kickoff-meeting)

**Member of Epic:** #16
