### ISSUE TITLE
Step 5: 📤 Define & prioritize MVP features

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/voyage-template#8]
**__Task Description__**
- [ ] Each team member should add their ideas to the [Project Vision & Feature Planning template](https://docs.google.com/document/d/1hod0AJXVe1T9HDqSwLr6VGXBz0HJ-HG4aM8JKoeBB00/edit?usp=sharing) before the team meeting
- [ ] Prioritize each feature - _Must Have_, _Should Have_, _Nice to Have_
- [ ] Meet with the team to review each feature & refine priorities

**__Technical Considerations__**
N/a

**__Additional Considerations__**
All _Must Have_ tasks will make up your MVP. Make sure that you control the scope of the project by limiting the number of _Must Have_ features to the ones you can reasonably complete by the end of Sprint 6.

Remember that you can always add new features once you complete the MVP.

**__Resources__**
[Choose a Project & create a Vision Statement (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#3-choose-a-project--create-a-vision-statement)
[Define & Prioritize MVP features (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#4-define--prioritize-mvp-features)

**Member of Epic:** #16
